(defun lfsort (xss)
  (let ((len-freq (make-hash-table)))
    (mapc (lambda (xs)
            (setf (gethash xs len-freq)
                  (count-if (lambda (ys)
                              (and (not (eq ys xs))
                                   (eq (length ys)
                                       (length xs))))
                            xss)))
          xss)
    (sort xss
          (lambda (ys zs)
            (< (gethash ys len-freq)
               (gethash zs len-freq))))))
