(defun compare-phis (n)
  (let ((start (get-universal-time)))
    (totient-phi n)
    (let ((end        (get-universal-time))
          (next-start (get-universal-time)))
      (totient-phi-improved n)
      (let ((next-end (get-universal-time)))
        (list (cons 'standard (- end      start))
              (cons 'improved (- next-end next-start)))))))
