(defun combination (n xs)
  (labels ((selections (ys i)
             (if (or (null ys)
                     (eq i 0))
                 (list nil)
                 (let ((other-combinations (selections (cdr ys)
                                                       (1- i))))
                   (append (mapcar (lambda (other)
                                     (cons (car ys)
                                           other))
                                   other-combinations)
                           (selections (cdr ys) i))))))
    (remove-if (lambda (ys)
                 (< (length ys) 3))
               (selections xs n))))
